// <auto-generated />
using DatabaseMotion.DBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DatabaseMotion.Migrations
{
    [DbContext(typeof(AppDBContext))]
    [Migration("20260118125708_SecondCreate")]
    partial class SecondCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DatabaseMotion.Models.Hotel", b =>
                {
                    b.Property<int>("HotelNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HotelNo"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("HotelNo");

                    b.ToTable("Hotels");

                    b.HasData(
                        new
                        {
                            HotelNo = 1,
                            Name = "Grand Hotel"
                        },
                        new
                        {
                            HotelNo = 2,
                            Name = "Seaside inn"
                        });
                });

            modelBuilder.Entity("DatabaseMotion.Models.Room", b =>
                {
                    b.Property<int>("RoomNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoomNo"));

                    b.Property<int>("HotelNo")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoomNo");

                    b.HasIndex("HotelNo");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            RoomNo = 1,
                            HotelNo = 1,
                            Price = 500m,
                            Type = "Single"
                        },
                        new
                        {
                            RoomNo = 2,
                            HotelNo = 1,
                            Price = 700m,
                            Type = "Double"
                        },
                        new
                        {
                            RoomNo = 3,
                            HotelNo = 2,
                            Price = 1200m,
                            Type = "Suite"
                        });
                });

            modelBuilder.Entity("DatabaseMotion.Models.Room", b =>
                {
                    b.HasOne("DatabaseMotion.Models.Hotel", "Hotel")
                        .WithMany("Rooms")
                        .HasForeignKey("HotelNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("DatabaseMotion.Models.Hotel", b =>
                {
                    b.Navigation("Rooms");
                });
#pragma warning restore 612, 618
        }
    }
}
